[package]
name = "cessc-sync-state-rpc"
version = "0.10.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
description = "A RPC handler to create sync states for light clients."
edition = "2021"
license = "Apache-2.0"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, features = ["client-core", "server", "macros"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
sc-chain-spec = { workspace = true }
sc-client-api = { workspace = true }
cessc-consensus-rrsc = { workspace = true }
sc-consensus-epochs = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sp-blockchain = { workspace = true }
sp-runtime = { workspace = true }
