
//! Autogenerated weights for `pallet_sminer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.0.0
//! DATE: 2024-11-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ytqaljn-virtual-machine`, CPU: `12th Gen Intel(R) Core(TM) i5-12400`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("cess-initial-devnet")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_sminer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/sminer/src/weights1.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_sminer`.
pub trait WeightInfo {
	fn migration_step() -> Weight;
}

/// Weights for `pallet_sminer` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Sminer::MinerItems` (r:2 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203243), added: 205718, mode: `MaxEncodedLen`)
	fn migration_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2582`
		//  Estimated: `412426`
		// Minimum execution time: 19_449_000 picoseconds.
		Weight::from_parts(20_632_000, 412426)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Sminer::MinerItems` (r:2 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203243), added: 205718, mode: `MaxEncodedLen`)
	fn migration_step() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2582`
		//  Estimated: `412426`
		// Minimum execution time: 19_449_000 picoseconds.
		Weight::from_parts(20_632_000, 412426)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
