
//! Autogenerated weights for `pallet_sminer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ytqaljn-virtual-machine`, CPU: `12th Gen Intel(R) Core(TM) i5-12400`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("cess-initial-devnet")`, DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_sminer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output=./pallets/sminer/src/weights_temp.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_sminer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_sminer::WeightInfo for WeightInfo<T> {
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::CounterForMinerItems` (r:1 w:1)
	/// Proof: `Sminer::CounterForMinerItems` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::RewardMap` (r:0 w:1)
	/// Proof: `Sminer::RewardMap` (`max_values`: None, `max_size`: Some(3592), added: 6067, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::StakingStartBlock` (r:0 w:1)
	/// Proof: `Sminer::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn regnstk() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `206644`
		// Minimum execution time: 52_536_000 picoseconds.
		Weight::from_parts(74_508_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::StakingStartBlock` (r:0 w:1)
	/// Proof: `Sminer::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn increase_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2666`
		//  Estimated: `206644`
		// Minimum execution time: 36_657_000 picoseconds.
		Weight::from_parts(41_160_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `TeeWorker::MasterPubkey` (r:1 w:0)
	/// Proof: `TeeWorker::MasterPubkey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TeeWorker::LastWork` (r:1 w:1)
	/// Proof: `TeeWorker::LastWork` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Sminer::AllMiner` (r:1 w:1)
	/// Proof: `Sminer::AllMiner` (`max_values`: Some(1), `max_size`: Some(6400004), added: 6400499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::MinerPublicKey` (r:0 w:1)
	/// Proof: `Sminer::MinerPublicKey` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn register_pois_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2845`
		//  Estimated: `6401489`
		// Minimum execution time: 99_071_000 picoseconds.
		Weight::from_parts(135_109_000, 0)
			.saturating_add(Weight::from_parts(0, 6401489))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	fn update_beneficiary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2563`
		//  Estimated: `206644`
		// Minimum execution time: 22_029_000 picoseconds.
		Weight::from_parts(37_224_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
