
//! Autogenerated weights for `pallet_sminer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-03-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ytqaljn-virtual-machine`, CPU: `12th Gen Intel(R) Core(TM) i5-12400`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("cess-initial-devnet")`, DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_sminer
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output=./pallets/sminer/src/weights_temp.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_sminer`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_sminer::WeightInfo for WeightInfo<T> {
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::CounterForMinerItems` (r:1 w:1)
	/// Proof: `Sminer::CounterForMinerItems` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::RewardMap` (r:0 w:1)
	/// Proof: `Sminer::RewardMap` (`max_values`: None, `max_size`: Some(3592), added: 6067, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::StakingStartBlock` (r:0 w:1)
	/// Proof: `Sminer::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn regnstk() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `183`
		//  Estimated: `206644`
		// Minimum execution time: 42_611_000 picoseconds.
		Weight::from_parts(59_427_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::StakingStartBlock` (r:0 w:1)
	/// Proof: `Sminer::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn increase_collateral() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2666`
		//  Estimated: `206644`
		// Minimum execution time: 36_983_000 picoseconds.
		Weight::from_parts(42_256_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `TeeWorker::MasterPubkey` (r:1 w:0)
	/// Proof: `TeeWorker::MasterPubkey` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TeeWorker::LastWork` (r:1 w:1)
	/// Proof: `TeeWorker::LastWork` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `Sminer::AllMiner` (r:1 w:1)
	/// Proof: `Sminer::AllMiner` (`max_values`: Some(1), `max_size`: Some(6400004), added: 6400499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::MinerPublicKey` (r:0 w:1)
	/// Proof: `Sminer::MinerPublicKey` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn register_pois_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2845`
		//  Estimated: `6401489`
		// Minimum execution time: 85_509_000 picoseconds.
		Weight::from_parts(104_125_000, 0)
			.saturating_add(Weight::from_parts(0, 6401489))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	fn update_beneficiary() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2563`
		//  Estimated: `206644`
		// Minimum execution time: 19_368_000 picoseconds.
		Weight::from_parts(21_827_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	fn update_peer_id() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2563`
		//  Estimated: `206644`
		// Minimum execution time: 18_734_000 picoseconds.
		Weight::from_parts(21_848_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:0)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::RewardMap` (r:1 w:1)
	/// Proof: `Sminer::RewardMap` (`max_values`: None, `max_size`: Some(3592), added: 6067, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `v` is `[1, 80]`.
	fn receive_reward(v: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3827 + v * (39 ±0)`
		//  Estimated: `206644`
		// Minimum execution time: 61_786_000 picoseconds.
		Weight::from_parts(76_000_911, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			// Standard Error: 15_160
			.saturating_add(Weight::from_parts(63_457, 0).saturating_mul(v.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Sminer::MinerLock` (r:1 w:1)
	/// Proof: `Sminer::MinerLock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::StakingStartBlock` (r:1 w:0)
	/// Proof: `Sminer::StakingStartBlock` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(10463), added: 12938, mode: `MaxEncodedLen`)
	fn miner_exit_prep() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3494`
		//  Estimated: `206644`
		// Minimum execution time: 50_839_000 picoseconds.
		Weight::from_parts(63_195_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:0)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:1)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::AllMiner` (r:1 w:1)
	/// Proof: `Sminer::AllMiner` (`max_values`: Some(1), `max_size`: Some(6400004), added: 6400499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::RestoralTarget` (r:0 w:1)
	/// Proof: `Sminer::RestoralTarget` (`max_values`: None, `max_size`: Some(116), added: 2591, mode: `MaxEncodedLen`)
	fn miner_exit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3685`
		//  Estimated: `6401489`
		// Minimum execution time: 29_809_000 picoseconds.
		Weight::from_parts(36_291_000, 0)
			.saturating_add(Weight::from_parts(0, 6401489))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn faucet_top_up() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `52`
		//  Estimated: `3593`
		// Minimum execution time: 49_460_000 picoseconds.
		Weight::from_parts(57_147_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `Sminer::FaucetRecordMap` (r:1 w:1)
	/// Proof: `Sminer::FaucetRecordMap` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn faucet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `220`
		//  Estimated: `3593`
		// Minimum execution time: 50_063_000 picoseconds.
		Weight::from_parts(55_430_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::CounterForMinerItems` (r:1 w:1)
	/// Proof: `Sminer::CounterForMinerItems` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Sminer::RewardMap` (r:0 w:1)
	/// Proof: `Sminer::RewardMap` (`max_values`: None, `max_size`: Some(3592), added: 6067, mode: `MaxEncodedLen`)
	fn regnstk_assign_staking() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `206644`
		// Minimum execution time: 26_164_000 picoseconds.
		Weight::from_parts(31_196_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `Sminer::MinerItems` (r:1 w:1)
	/// Proof: `Sminer::MinerItems` (`max_values`: None, `max_size`: Some(203179), added: 205654, mode: `MaxEncodedLen`)
	fn increase_declaration_space() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3411`
		//  Estimated: `206644`
		// Minimum execution time: 26_482_000 picoseconds.
		Weight::from_parts(29_798_000, 0)
			.saturating_add(Weight::from_parts(0, 206644))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
