[package]
name = "cp-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.14", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
sp-std = { default-features = false, git = 'https://github.com/CESSProject/substrate.git', branch = 'monthly-2022-04-cess', version = '4.0.0-dev'}
cp-cess-common = { version = "0.1.0", path = '../common', default-features = false }
serde_json = "1.0.79"

# verify sgx signture
webpki = { package = "webpki", path = '../../utils/webpki', default-features = false }
base64 = { default-features = false, features = ["alloc"], version = "0.12.2" }
sp-application-crypto = { version = '6.0.0', branch = 'monthly-2022-04-cess', git = 'https://github.com/CESSProject/substrate.git', default-features = false }
sp-io = { version = "6.0.0", default-features = false, branch = 'monthly-2022-04-cess', git = 'https://github.com/CESSProject/substrate.git' }


[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"sp-std/std",
	"webpki/std",
	"sp-application-crypto/std",
	"sp-io/std",
	"cp-cess-common/std",

]

