// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_audit
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-08-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("cess-initial-devnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_audit
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./c-pallets/audit/src/weights_demo.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_audit.
pub trait WeightInfo {
	fn submit_idle_proof() -> Weight;
	fn submit_service_proof() -> Weight;
	fn submit_verify_idle_result() -> Weight;
	fn submit_verify_service_result() -> Weight;
}

/// Weights for pallet_audit using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Audit ChallengeSnapShot (r:1 w:1)
	// Storage: TeeWorker TeeWorkerMap (r:2 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: Audit UnverifyIdleProof (r:1 w:1)
	fn submit_idle_proof() -> Weight {
		(172_133_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Audit ChallengeSnapShot (r:1 w:1)
	// Storage: TeeWorker TeeWorkerMap (r:2 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: Audit UnverifyServiceProof (r:1 w:1)
	fn submit_service_proof() -> Weight {
		(144_386_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Audit UnverifyIdleProof (r:1 w:1)
	// Storage: Audit ChallengeSnapShot (r:1 w:0)
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Audit VerifyResult (r:1 w:1)
	// Storage: Sminer RewardMap (r:1 w:1)
	// Storage: Sminer CurrencyReward (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Audit CountedIdleFailed (r:0 w:1)
	fn submit_verify_idle_result() -> Weight {
		(1_722_404_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: Audit UnverifyServiceProof (r:1 w:1)
	// Storage: Audit ChallengeSnapShot (r:1 w:0)
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Audit VerifyResult (r:1 w:1)
	// Storage: Sminer RewardMap (r:1 w:1)
	// Storage: Sminer CurrencyReward (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Audit CountedIdleFailed (r:0 w:1)
	fn submit_verify_service_result() -> Weight {
		(1_768_883_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Audit ChallengeSnapShot (r:1 w:1)
	// Storage: TeeWorker TeeWorkerMap (r:2 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: Audit UnverifyIdleProof (r:1 w:1)
	fn submit_idle_proof() -> Weight {
		(172_133_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Audit ChallengeSnapShot (r:1 w:1)
	// Storage: TeeWorker TeeWorkerMap (r:2 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: Audit UnverifyServiceProof (r:1 w:1)
	fn submit_service_proof() -> Weight {
		(144_386_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Audit UnverifyIdleProof (r:1 w:1)
	// Storage: Audit ChallengeSnapShot (r:1 w:0)
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Audit VerifyResult (r:1 w:1)
	// Storage: Sminer RewardMap (r:1 w:1)
	// Storage: Sminer CurrencyReward (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Audit CountedIdleFailed (r:0 w:1)
	fn submit_verify_idle_result() -> Weight {
		(1_722_404_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: Audit UnverifyServiceProof (r:1 w:1)
	// Storage: Audit ChallengeSnapShot (r:1 w:0)
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Audit VerifyResult (r:1 w:1)
	// Storage: Sminer RewardMap (r:1 w:1)
	// Storage: Sminer CurrencyReward (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Audit CountedIdleFailed (r:0 w:1)
	fn submit_verify_service_result() -> Weight {
		(1_768_883_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
}