// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_storage_handler
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-08-24, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("cess-initial-devnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_storage_handler
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./c-pallets/storage-handler/src/weights_demo.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_storage_handler.
pub trait WeightInfo {
	fn buy_space() -> Weight;
	fn expansion_space() -> Weight;
	fn renewal_space() -> Weight;
}

/// Weights for pallet_storage_handler using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: StorageHandler PurchasedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:0)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn buy_space() -> Weight {
		(92_002_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: StorageHandler PurchasedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:0)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:0)
	fn expansion_space() -> Weight {
		(101_652_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn renewal_space() -> Weight {
		(76_537_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: StorageHandler PurchasedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:0)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn buy_space() -> Weight {
		(92_002_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: StorageHandler PurchasedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:0)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:0)
	fn expansion_space() -> Weight {
		(101_652_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn renewal_space() -> Weight {
		(76_537_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
}