[package]
name = "pallet-cess-pause"
authors = ["CESS LAB"]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/CESSProject/cess"
description = "FRAME pallet for cess pause"
readme = "README.md"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }

frame-support = { workspace = true }
frame-system = { workspace = true }
pallet-tx-pause = { workspace = true }
sp-std = { workspace = true }



[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "sp-std/std",
    "pallet-tx-pause/std",
    "frame-support/std",
    "frame-system/std",
]