// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_file_bank
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-01-04, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("cess-initial-devnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_file_bank
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./c-pallets/file-bank/src/weights_demo.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_file_bank.
pub trait WeightInfo {
	fn upload_filler(v: u32, ) -> Weight;
	fn upload_autonomy_file(v: u32, ) -> Weight;
	fn delete_autonomy_file() -> Weight;
	fn buy_space() -> Weight;
	fn expansion_space() -> Weight;
	fn renewal_space() -> Weight;
	fn create_bucket() -> Weight;
	fn delete_bucket() -> Weight;
	fn upload_deal() -> Weight;
	fn pack_deal(v: u32, ) -> Weight;
}

/// Weights for pallet_file_bank using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Sminer TotalIdleSpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank FillerMap (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:1 w:1)
	fn upload_filler(v: u32, ) -> Weight {
		(51_655_000 as Weight)
			// Standard Error: 174_000
			.saturating_add((32_234_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(v as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((2 as Weight).saturating_mul(v as Weight)))
	}
	// Storage: FileBank UniqueHashMap (r:1 w:1)
	// Storage: Sminer TotalAutonomySpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank AutonomyFile (r:0 w:1)
	fn upload_autonomy_file(v: u32, ) -> Weight {
		(60_387_000 as Weight)
			// Standard Error: 129_000
			.saturating_add((24_882_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(v as Weight)))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(v as Weight)))
	}
	// Storage: FileBank AutonomyFile (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Sminer TotalAutonomySpace (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:0 w:2)
	fn delete_autonomy_file() -> Weight {
		(83_644_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: Sminer PurchasedSpace (r:1 w:1)
	// Storage: Sminer TotalIdleSpace (r:1 w:0)
	// Storage: Sminer TotalServiceSpace (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn buy_space() -> Weight {
		(81_306_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Sminer PurchasedSpace (r:1 w:1)
	// Storage: Sminer TotalIdleSpace (r:1 w:0)
	// Storage: Sminer TotalServiceSpace (r:1 w:0)
	fn expansion_space() -> Weight {
		(86_114_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn renewal_space() -> Weight {
		(75_268_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn create_bucket() -> Weight {
		(29_841_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn delete_bucket() -> Weight {
		(34_120_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank UniqueHashMap (r:2 w:2)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileMap SchedulerMap (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_deal() -> Weight {
		(96_296_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:0)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Sminer TotalServiceSpace (r:1 w:1)
	// Storage: Sminer TotalIdleSpace (r:1 w:1)
	// Storage: FileBank FillerMap (r:4 w:3)
	// Storage: FileBank InvalidFile (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:0 w:3)
	fn pack_deal(v: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 6_625_000
			.saturating_add((710_792_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(11 as Weight))
			.saturating_add(T::DbWeight::get().reads((3 as Weight).saturating_mul(v as Weight)))
			.saturating_add(T::DbWeight::get().writes(11 as Weight))
			.saturating_add(T::DbWeight::get().writes((6 as Weight).saturating_mul(v as Weight)))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: Sminer TotalIdleSpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank FillerMap (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:1 w:1)
	fn upload_filler(v: u32, ) -> Weight {
		(51_655_000 as Weight)
			// Standard Error: 174_000
			.saturating_add((32_234_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().reads((2 as Weight).saturating_mul(v as Weight)))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes((2 as Weight).saturating_mul(v as Weight)))
	}
	// Storage: FileBank UniqueHashMap (r:1 w:1)
	// Storage: Sminer TotalAutonomySpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank AutonomyFile (r:0 w:1)
	fn upload_autonomy_file(v: u32, ) -> Weight {
		(60_387_000 as Weight)
			// Standard Error: 129_000
			.saturating_add((24_882_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(v as Weight)))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(v as Weight)))
	}
	// Storage: FileBank AutonomyFile (r:1 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Sminer TotalAutonomySpace (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:0 w:2)
	fn delete_autonomy_file() -> Weight {
		(83_644_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: Sminer PurchasedSpace (r:1 w:1)
	// Storage: Sminer TotalIdleSpace (r:1 w:0)
	// Storage: Sminer TotalServiceSpace (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn buy_space() -> Weight {
		(81_306_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	// Storage: Sminer PurchasedSpace (r:1 w:1)
	// Storage: Sminer TotalIdleSpace (r:1 w:0)
	// Storage: Sminer TotalServiceSpace (r:1 w:0)
	fn expansion_space() -> Weight {
		(86_114_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank UnitPrice (r:1 w:0)
	// Storage: System Account (r:2 w:2)
	fn renewal_space() -> Weight {
		(75_268_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn create_bucket() -> Weight {
		(29_841_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn delete_bucket() -> Weight {
		(34_120_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank UniqueHashMap (r:2 w:2)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileMap SchedulerMap (r:1 w:0)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_deal() -> Weight {
		(96_296_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(7 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:0)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank UserOwnedSpace (r:1 w:1)
	// Storage: SchedulerCredit CurrentCounters (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Sminer TotalServiceSpace (r:1 w:1)  
	// Storage: Sminer TotalIdleSpace (r:1 w:1)
	// Storage: FileBank FillerMap (r:4 w:3)
	// Storage: FileBank InvalidFile (r:1 w:1)
	// Storage: FileBank UniqueHashMap (r:0 w:3)
	fn pack_deal(v: u32, ) -> Weight {
		(0 as Weight)
			// Standard Error: 6_625_000
			.saturating_add((710_792_000 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(11 as Weight))
			.saturating_add(RocksDbWeight::get().reads((3 as Weight).saturating_mul(v as Weight)))
			.saturating_add(RocksDbWeight::get().writes(11 as Weight))
			.saturating_add(RocksDbWeight::get().writes((6 as Weight).saturating_mul(v as Weight)))
	}
}