// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_file_bank
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-08-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("cess-initial-testnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-testnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_file_bank
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./c-pallets/file-bank/src/weights_demo.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_file_bank.
pub trait WeightInfo {
	fn upload_declaration(v: u32, ) -> Weight;
	fn upload_declaration_expected_max(v: u32, ) -> Weight;
	fn transfer_report(v: u32, ) -> Weight;
	fn transfer_report_last(v: u32, ) -> Weight;
	fn upload_declaration_fly_upload(v: u32, ) -> Weight;
}

/// Weights for pallet_file_bank using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration(v: u32, ) -> Weight {
		(217_824_383 as Weight)
			// Standard Error: 92_976
			.saturating_add((1_650_262 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(11 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:15 w:0)
	// Storage: Sminer MinerItems (r:15 w:2)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration_expected_max(v: u32, ) -> Weight {
		(519_638_637 as Weight)
			// Standard Error: 131_995
			.saturating_add((1_078_921 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(36 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	fn transfer_report(v: u32, ) -> Weight {
		(75_478_863 as Weight)
			// Standard Error: 31_395
			.saturating_add((869_952 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:3 w:3)
	// Storage: FileBank TaskFailedCount (r:3 w:3)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	fn transfer_report_last(v: u32, ) -> Weight {
		(192_801_299 as Weight)
			// Standard Error: 61_091
			.saturating_add((4_995_701 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(17 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	fn upload_declaration_fly_upload(v: u32, ) -> Weight {
		(118_765_783 as Weight)
			// Standard Error: 41_245
			.saturating_add((1_000_304 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration(v: u32, ) -> Weight {
		(217_824_383 as Weight)
			// Standard Error: 92_976
			.saturating_add((1_650_262 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(11 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:15 w:0)
	// Storage: Sminer MinerItems (r:15 w:2)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration_expected_max(v: u32, ) -> Weight {
		(519_638_637 as Weight)
			// Standard Error: 131_995
			.saturating_add((1_078_921 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(36 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	fn transfer_report(v: u32, ) -> Weight {
		(75_478_863 as Weight)
			// Standard Error: 31_395
			.saturating_add((869_952 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:3 w:3)
	// Storage: FileBank TaskFailedCount (r:3 w:3)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	fn transfer_report_last(v: u32, ) -> Weight {
		(192_801_299 as Weight)
			// Standard Error: 61_091
			.saturating_add((4_995_701 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(16 as Weight))
			.saturating_add(RocksDbWeight::get().writes(17 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	fn upload_declaration_fly_upload(v: u32, ) -> Weight {
		(118_765_783 as Weight)
			// Standard Error: 41_245
			.saturating_add((1_000_304 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
}