// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_file_bank
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-08-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("cess-initial-testnet"), DB CACHE: 1024

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-testnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_file_bank
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./c-pallets/file-bank/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_file_bank.
pub trait WeightInfo {
	fn cert_idle_space() -> Weight;
	fn upload_declaration(v: u32, ) -> Weight;
	fn upload_declaration_expected_max(v: u32, ) -> Weight;
	fn transfer_report(v: u32, ) -> Weight;
	fn transfer_report_last(v: u32, ) -> Weight;
	fn upload_declaration_fly_upload(v: u32, ) -> Weight;
	fn deal_reassign_miner(v: u32, ) -> Weight;
	fn deal_reassign_miner_exceed_limit(v: u32, ) -> Weight;
	fn calculate_end(v: u32, ) -> Weight;
	fn replace_idle_space() -> Weight;
	fn delete_file(v: u32, ) -> Weight;
	fn create_bucket() -> Weight;
	fn delete_bucket() -> Weight;
	fn generate_restoral_order() -> Weight;
	fn claim_restoral_order() -> Weight;
	fn restoral_order_complete() -> Weight;
	fn claim_restoral_noexist_order() -> Weight;
}

/// Weights for pallet_file_bank using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	fn cert_idle_space() -> Weight {
		(2_035_393_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration(v: u32, ) -> Weight {
		(297_861_001 as Weight)
			// Standard Error: 346_539
			.saturating_add((843_614 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(11 as Weight))
			.saturating_add(T::DbWeight::get().writes(7 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:15 w:0)
	// Storage: Sminer MinerItems (r:15 w:2)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration_expected_max(v: u32, ) -> Weight {
		(654_378_586 as Weight)
			// Standard Error: 780_625
			.saturating_add((2_102_101 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(36 as Weight))
			.saturating_add(T::DbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	fn transfer_report(v: u32, ) -> Weight {
		(94_546_253 as Weight)
			// Standard Error: 308_157
			.saturating_add((4_602_776 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:3 w:3)
	// Storage: FileBank TaskFailedCount (r:3 w:3)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	fn transfer_report_last(v: u32, ) -> Weight {
		(301_764_084 as Weight)
			// Standard Error: 459_737
			.saturating_add((6_315_999 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(16 as Weight))
			.saturating_add(T::DbWeight::get().writes(17 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	fn upload_declaration_fly_upload(v: u32, ) -> Weight {
		(172_998_901 as Weight)
			// Standard Error: 205_507
			.saturating_add((937_477 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:18 w:3)
	// Storage: Sminer MinerItems (r:18 w:6)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn deal_reassign_miner(v: u32, ) -> Weight {
		(646_629_189 as Weight)
			// Standard Error: 835_742
			.saturating_add((4_832_563 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(41 as Weight))
			.saturating_add(T::DbWeight::get().writes(12 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:3 w:3)
	fn deal_reassign_miner_exceed_limit(v: u32, ) -> Weight {
		(173_729_899 as Weight)
			// Standard Error: 262_150
			.saturating_add((1_847_301 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: Sminer MinerItems (r:3 w:3)
	// Storage: FileBank File (r:1 w:1)
	fn calculate_end(v: u32, ) -> Weight {
		(215_140_030 as Weight)
			// Standard Error: 358_010
			.saturating_add((5_061_677 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:1 w:1)
	fn replace_idle_space() -> Weight {
		(1_764_110_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank File (r:1 w:1)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:3 w:0)
	// Storage: Sminer MinerItems (r:3 w:3)
	fn delete_file(v: u32, ) -> Weight {
		(266_794_806 as Weight)
			// Standard Error: 396_291
			.saturating_add((5_400_689 as Weight).saturating_mul(v as Weight))
			.saturating_add(T::DbWeight::get().reads(10 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn create_bucket() -> Weight {
		(67_171_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn delete_bucket() -> Weight {
		(53_851_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	fn generate_restoral_order() -> Weight {
		(163_062_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
	// Storage: Sminer MinerItems (r:1 w:0)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	fn claim_restoral_order() -> Weight {
		(107_814_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(2 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: Sminer MinerItems (r:2 w:2)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:1 w:0)
	fn restoral_order_complete() -> Weight {
		(231_953_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(5 as Weight))
	}
	// Storage: Sminer MinerItems (r:1 w:0)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:1 w:0)
	// Storage: FileBank File (r:1 w:1)
	fn claim_restoral_noexist_order() -> Weight {
		(134_762_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	fn cert_idle_space() -> Weight {
		(2_035_393_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration(v: u32, ) -> Weight {
		(297_861_001 as Weight)
			// Standard Error: 346_539
			.saturating_add((843_614 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(11 as Weight))
			.saturating_add(RocksDbWeight::get().writes(7 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:0)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:15 w:0)
	// Storage: Sminer MinerItems (r:15 w:2)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	// Storage: FileBank DealMap (r:0 w:1)
	fn upload_declaration_expected_max(v: u32, ) -> Weight {
		(654_378_586 as Weight)
			// Standard Error: 780_625
			.saturating_add((2_102_101 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(36 as Weight))
			.saturating_add(RocksDbWeight::get().writes(6 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	fn transfer_report(v: u32, ) -> Weight {
		(94_546_253 as Weight)
			// Standard Error: 308_157
			.saturating_add((4_602_776 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:3 w:3)
	// Storage: FileBank TaskFailedCount (r:3 w:3)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalIdleSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:2 w:2)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: FileBank File (r:0 w:1)
	fn transfer_report_last(v: u32, ) -> Weight {
		(301_764_084 as Weight)
			// Standard Error: 459_737
			.saturating_add((6_315_999 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(16 as Weight))
			.saturating_add(RocksDbWeight::get().writes(17 as Weight))
	}
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	fn upload_declaration_fly_upload(v: u32, ) -> Weight {
		(172_998_901 as Weight)
			// Standard Error: 205_507
			.saturating_add((937_477 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: Sminer AllMiner (r:1 w:0)
	// Storage: Babe AuthorVrfRandomness (r:1 w:0)
	// Storage: FileBank TaskFailedCount (r:18 w:3)
	// Storage: Sminer MinerItems (r:18 w:6)
	// Storage: Scheduler Lookup (r:1 w:1)
	// Storage: Scheduler Agenda (r:1 w:1)
	fn deal_reassign_miner(v: u32, ) -> Weight {
		(646_629_189 as Weight)
			// Standard Error: 835_742
			.saturating_add((4_832_563 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(41 as Weight))
			.saturating_add(RocksDbWeight::get().writes(12 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: Sminer MinerItems (r:3 w:3)
	fn deal_reassign_miner_exceed_limit(v: u32, ) -> Weight {
		(173_729_899 as Weight)
			// Standard Error: 262_150
			.saturating_add((1_847_301 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: FileBank DealMap (r:1 w:1)
	// Storage: Sminer MinerItems (r:3 w:3)
	// Storage: FileBank File (r:1 w:1)
	fn calculate_end(v: u32, ) -> Weight {
		(215_140_030 as Weight)
			// Standard Error: 358_010
			.saturating_add((5_061_677 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(5 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: TeeWorker TeePodr2Pk (r:1 w:0)
	// Storage: Sminer MinerItems (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:1 w:1)
	fn replace_idle_space() -> Weight {
		(1_764_110_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(3 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank File (r:1 w:1)
	// Storage: StorageHandler UserOwnedSpace (r:1 w:1)
	// Storage: StorageHandler TotalServiceSpace (r:1 w:1)
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserHoldFileList (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:3 w:0)
	// Storage: Sminer MinerItems (r:3 w:3)
	fn delete_file(v: u32, ) -> Weight {
		(266_794_806 as Weight)
			// Standard Error: 396_291
			.saturating_add((5_400_689 as Weight).saturating_mul(v as Weight))
			.saturating_add(RocksDbWeight::get().reads(10 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn create_bucket() -> Weight {
		(67_171_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank Bucket (r:1 w:1)
	// Storage: FileBank UserBucketList (r:1 w:1)
	fn delete_bucket() -> Weight {
		(53_851_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	fn generate_restoral_order() -> Weight {
		(163_062_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
	// Storage: Sminer MinerItems (r:1 w:0)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	fn claim_restoral_order() -> Weight {
		(107_814_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(2 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: Sminer MinerItems (r:2 w:2)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: FileBank File (r:1 w:1)
	// Storage: FileBank PendingReplacements (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:1 w:0)
	fn restoral_order_complete() -> Weight {
		(231_953_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(6 as Weight))
			.saturating_add(RocksDbWeight::get().writes(5 as Weight))
	}
	// Storage: Sminer MinerItems (r:1 w:0)
	// Storage: FileBank RestoralOrder (r:1 w:1)
	// Storage: Sminer RestoralTarget (r:1 w:0)
	// Storage: FileBank File (r:1 w:1)
	fn claim_restoral_noexist_order() -> Weight {
		(134_762_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(2 as Weight))
	}
}