
//! Autogenerated weights for `pallet_storage_handler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2024-06-24, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ytqaljn-virtual-machine`, CPU: `12th Gen Intel(R) Core(TM) i5-12400`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("cess-initial-devnet")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/cess-node
// benchmark
// pallet
// --chain
// cess-initial-devnet
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_storage_handler
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --template=./.maintain/frame-weight-template.hbs
// --output=./pallets/storage-handler/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_storage_handler`.
pub trait WeightInfo {
	fn mint_territory() -> Weight;
	fn expanding_territory() -> Weight;
	fn renewal_territory() -> Weight;
	fn treeitory_consignment() -> Weight;
	fn buy_consignment() -> Weight;
	fn exec_consignment() -> Weight;
	fn cancel_consignment() -> Weight;
	fn cancel_purchase_action() -> Weight;
	fn territory_grants() -> Weight;
	fn territory_rename() -> Weight;
	fn create_order() -> Weight;
	fn exec_order() -> Weight;
	fn reactivate_territory() -> Weight;
}

/// Weights for `pallet_storage_handler` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn mint_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `603`
		//  Estimated: `6196`
		// Minimum execution time: 65_031_000 picoseconds.
		Weight::from_parts(68_175_000, 6196)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn expanding_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `802`
		//  Estimated: `6196`
		// Minimum execution time: 54_590_000 picoseconds.
		Weight::from_parts(57_599_000, 6196)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:2 w:2)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:2)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryExpired` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryExpired` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn renewal_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `808`
		//  Estimated: `6196`
		// Minimum execution time: 100_984_000 picoseconds.
		Weight::from_parts(103_492_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn treeitory_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `3698`
		// Minimum execution time: 27_278_000 picoseconds.
		Weight::from_parts(28_334_000, 3698)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn buy_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `110487`
		// Minimum execution time: 26_461_000 picoseconds.
		Weight::from_parts(34_684_000, 110487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	fn exec_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1011`
		//  Estimated: `6196`
		// Minimum execution time: 63_599_000 picoseconds.
		Weight::from_parts(66_427_000, 6196)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn cancel_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `659`
		//  Estimated: `3698`
		// Minimum execution time: 20_154_000 picoseconds.
		Weight::from_parts(31_057_000, 3698)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn cancel_purchase_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `651`
		//  Estimated: `110487`
		// Minimum execution time: 27_678_000 picoseconds.
		Weight::from_parts(40_002_000, 110487)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn territory_grants() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `3698`
		// Minimum execution time: 17_520_000 picoseconds.
		Weight::from_parts(18_657_000, 3698)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn territory_rename() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `3698`
		// Minimum execution time: 26_201_000 picoseconds.
		Weight::from_parts(27_089_000, 3698)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:0)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PayOrder` (r:0 w:1)
	/// Proof: `StorageHandler::PayOrder` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	fn create_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `3698`
		// Minimum execution time: 18_134_000 picoseconds.
		Weight::from_parts(18_997_000, 3698)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageHandler::PayOrder` (r:1 w:0)
	/// Proof: `StorageHandler::PayOrder` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn exec_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739`
		//  Estimated: `6196`
		// Minimum execution time: 64_761_000 picoseconds.
		Weight::from_parts(71_674_000, 6196)
			.saturating_add(T::DbWeight::get().reads(10_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn reactivate_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `6196`
		// Minimum execution time: 64_591_000 picoseconds.
		Weight::from_parts(66_512_000, 6196)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn mint_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `603`
		//  Estimated: `6196`
		// Minimum execution time: 65_031_000 picoseconds.
		Weight::from_parts(68_175_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn expanding_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `802`
		//  Estimated: `6196`
		// Minimum execution time: 54_590_000 picoseconds.
		Weight::from_parts(57_599_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:2 w:2)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:2)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryExpired` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryExpired` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn renewal_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `808`
		//  Estimated: `6196`
		// Minimum execution time: 100_984_000 picoseconds.
		Weight::from_parts(103_492_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn treeitory_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `590`
		//  Estimated: `3698`
		// Minimum execution time: 27_278_000 picoseconds.
		Weight::from_parts(28_334_000, 3698)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn buy_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `110487`
		// Minimum execution time: 26_461_000 picoseconds.
		Weight::from_parts(34_684_000, 110487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	fn exec_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1011`
		//  Estimated: `6196`
		// Minimum execution time: 63_599_000 picoseconds.
		Weight::from_parts(66_427_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	fn cancel_consignment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `659`
		//  Estimated: `3698`
		// Minimum execution time: 20_154_000 picoseconds.
		Weight::from_parts(31_057_000, 3698)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `StorageHandler::Consignment` (r:1 w:1)
	/// Proof: `StorageHandler::Consignment` (`max_values`: None, `max_size`: Some(135), added: 2610, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Lookup` (r:1 w:1)
	/// Proof: `Scheduler::Lookup` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Scheduler::Agenda` (r:1 w:1)
	/// Proof: `Scheduler::Agenda` (`max_values`: None, `max_size`: Some(107022), added: 109497, mode: `MaxEncodedLen`)
	fn cancel_purchase_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `651`
		//  Estimated: `110487`
		// Minimum execution time: 27_678_000 picoseconds.
		Weight::from_parts(40_002_000, 110487)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn territory_grants() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `3698`
		// Minimum execution time: 17_520_000 picoseconds.
		Weight::from_parts(18_657_000, 3698)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:2)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	fn territory_rename() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `604`
		//  Estimated: `3698`
		// Minimum execution time: 26_201_000 picoseconds.
		Weight::from_parts(27_089_000, 3698)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:0)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PayOrder` (r:0 w:1)
	/// Proof: `StorageHandler::PayOrder` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	fn create_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `497`
		//  Estimated: `3698`
		// Minimum execution time: 18_134_000 picoseconds.
		Weight::from_parts(18_997_000, 3698)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `StorageHandler::PayOrder` (r:1 w:0)
	/// Proof: `StorageHandler::PayOrder` (`max_values`: None, `max_size`: Some(174), added: 2649, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `Babe::AuthorVrfRandomness` (r:1 w:0)
	/// Proof: `Babe::AuthorVrfRandomness` (`max_values`: Some(1), `max_size`: Some(33), added: 528, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryKey` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryKey` (`max_values`: None, `max_size`: Some(144), added: 2619, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn exec_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `739`
		//  Estimated: `6196`
		// Minimum execution time: 64_761_000 picoseconds.
		Weight::from_parts(71_674_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(10_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `StorageHandler::Territory` (r:1 w:1)
	/// Proof: `StorageHandler::Territory` (`max_values`: None, `max_size`: Some(233), added: 2708, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::UnitPrice` (r:1 w:0)
	/// Proof: `StorageHandler::UnitPrice` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::PurchasedSpace` (r:1 w:1)
	/// Proof: `StorageHandler::PurchasedSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalIdleSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalIdleSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TotalServiceSpace` (r:1 w:0)
	/// Proof: `StorageHandler::TotalServiceSpace` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozenCounter` (r:1 w:1)
	/// Proof: `StorageHandler::TerritoryFrozenCounter` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `StorageHandler::TerritoryFrozen` (r:0 w:1)
	/// Proof: `StorageHandler::TerritoryFrozen` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	fn reactivate_territory() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `779`
		//  Estimated: `6196`
		// Minimum execution time: 64_591_000 picoseconds.
		Weight::from_parts(66_512_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
}
