[package]
name = "pallet-storage-handler"
authors = ["CESS LAB"]
version = "0.7.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/CESSProject/cess"
description = "FRAME pallet for sminer management"
readme = "README.md"

[dependencies]
log = { workspace = true }
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, optional = true }

# substrate pallet
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-benchmarking = { workspace = true }
pallet-balances = { workspace = true }

# substrate primitives 
sp-core = { workspace = true }
sp-std = { workspace = true }
sp-runtime = { workspace = true }

# local dependencies
cp-cess-common = { workspace = true }
pallet-cess-treasury = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
	"serde",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "sp-runtime/std",
    "frame-benchmarking/std",
    "pallet-cess-treasury/std",
]

try-runtime = [ "frame-support/try-runtime" ]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
]