[package]
name = "ces-rrsc-vrf-solver"
version = "0.1.0"
description = "RRSC consensus algorithm"
authors.workspace = true
edition.workspace = true

[dependencies]
codec = { workspace = true, default-features = false, features = ["derive"] }
frame-election-provider-support = { workspace = true }
frame-support = { workspace = true }
log = { workspace = true }
pallet-babe = { workspace = true }
sp-npos-elections = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-election-provider-support/std",
	"frame-support/std",
	"log/std",
	"pallet-babe/std",
	"sp-npos-elections/std",
	"sp-std/std",
]