[package]
name = "cifrost"
version = "0.1.3"
authors = ["CESS Network"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["rustls-tls", "socks"] }
hex = { workspace = true }
base64 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
rand = { workspace = true }
clap = { workspace = true, features = ["derive"] }
tonic ={ workspace = true }
async-trait = { workspace = true }

frame-system = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-consensus-grandpa = { workspace = true }
sp-trie = { workspace = true }
sc-consensus-grandpa = { workspace = true }
parity-scale-codec = { workspace = true }
scale-info = { workspace = true }
hash-db = { workspace = true }

pallet-grandpa = { workspace = true }
pallet-indices = { workspace = true }
pallet-balances = { workspace = true }

ces-sanitized-logger ={ workspace = true }
ces-types = { workspace = true }
ces-trie-storage = { workspace = true }
ces-node-rpc-ext = { workspace = true }
ces-mq = { workspace = true }
cestory-api = { workspace = true, features = ["ceseal-client", "std"] }
cesxt = { workspace = true }


[features]
only-attestation = [
	"cestory-api/only-attestation"
]
verify-cesealbin = [
	"cestory-api/verify-cesealbin"
]