[package]
name = "cessc-consensus-rrsc"
version = "0.10.0-dev"
authors = ["CESS"]
description = "RRSC consensus algorithm"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://cess.one"
repository = "https://github.com/CESSProject/substrate"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
scale-info = { workspace = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.2.2", features = ["derive"] }
futures = { workspace = true }
log = { workspace = true }
num-bigint = { workspace = true }
num-rational = { workspace = true }
num-traits = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
fork-tree = { workspace = true }
prometheus-endpoint = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus = { workspace = true }
sc-consensus-epochs = { workspace = true }
sc-consensus-slots = { workspace = true }
sc-keystore = { workspace = true }
sc-telemetry = { workspace = true }
sp-api = { workspace = true }
sp-application-crypto = { workspace = true }
sp-block-builder = { workspace = true, features = ["std"]}
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-core = { workspace = true }
sp-inherents = { workspace = true }
sp-keystore = { workspace = true }
sp-runtime = { workspace = true }
cessp-consensus-rrsc = { workspace = true, features = ["std"]}

[dev-dependencies]
rand_chacha = { workspace = true }
sc-block-builder = { workspace = true }
sp-keyring = { workspace = true }
sc-network = { workspace = true }
sc-network-test = { workspace = true }
sp-timestamp = { workspace = true }
sp-tracing = { workspace = true }
substrate-test-runtime-client = { workspace = true }
tokio = { workspace = true }
