name: build-and-test

on:
  push:
    branches: [ "main" , "dev"]
  pull_request:
    branches: [ "main" , "dev"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - uses: actions/checkout@v3
      - name: install toolchain
        uses: 0xbillw/install-rust-substrate-action@main
      - name: Build
        run: cargo build -r --verbose
      # We don't run cargo test for now.
      # - name: Run tests
      #   run: cargo test -r --verbose
